// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default function handler(req, res) {
  res
    .status(200)
    .json([{
      "Task Name": "01",
      id: "01",
      Brandname: "nike",
      Tier: "tier1",
      Type: "image",
      "Token Progress": "55%",
      "Target Reach progress": "55%",
      Budget: "5666",
      Impressions: "5000",
      Reach: "3500",
      "Engagement Rate": "4.96%",
      "Tokens Dispensed": "56000",
      "Stars dispensed": "30000",
      Tickets: "3500",
      "Bonus Set": "Default",
      "Tokens Added": "8900",
      Viewers: "3000",
      Incomplete: "2000",
      "Days Active": "36 days",
      "End Date": "1/3/12",
      State: "Active",
    },{
        "Task Name": "01",
        id: "01",
        Brandname: "nike",
        Tier: "tier1",
        Type: "image",
        "Token Progress": "55%",
        "Target Reach progress": "55%",
        Budget: "5666",
        Impressions: "5000",
        Reach: "3500",
        "Engagement Rate": "4.96%",
        "Tokens Dispensed": "56000",
        "Stars dispensed": "30000",
        Tickets: "3500",
        "Bonus Set": "Default",
        "Tokens Added": "8900",
        Viewers: "3000",
        Incomplete: "2000",
        "Days Active": "36 days",
        "End Date": "1/3/12",
        State: "Active",
      },
    {
        "Task Name": "01",
        id: "01",
        Brandname: "nike",
        Tier: "tier1",
        Type: "image",
        "Token Progress": "55%",
        "Target Reach progress": "55%",
        Budget: "5666",
        Impressions: "5000",
        Reach: "3500",
        "Engagement Rate": "4.96%",
        "Tokens Dispensed": "56000",
        "Stars dispensed": "30000",
        Tickets: "3500",
        "Bonus Set": "Default",
        "Tokens Added": "8900",
        Viewers: "3000",
        Incomplete: "2000",
        "Days Active": "36 days",
        "End Date": "1/3/12",
        State: "Active",
      },
    {
        "Task Name": "01",
        id: "01",
        Brandname: "nike",
        Tier: "tier1",
        Type: "image",
        "Token Progress": "55%",
        "Target Reach progress": "55%",
        Budget: "5666",
        Impressions: "5000",
        Reach: "3500",
        "Engagement Rate": "4.96%",
        "Tokens Dispensed": "56000",
        "Stars dispensed": "30000",
        Tickets: "3500",
        "Bonus Set": "Default",
        "Tokens Added": "8900",
        Viewers: "3000",
        Incomplete: "2000",
        "Days Active": "36 days",
        "End Date": "1/3/12",
        State: "Active",
      }]);
}
