import Head from "next/head";
import useSwr from "swr";
import { Typography, Space } from "antd";
import Table from "../components/table";
import styles from "../styles/Home.module.css";

const { Link, Title } = Typography;

const fetcher = (url) => fetch(url).then((res) => res.json());


const columns = [
  {
    title: "Username",
    dataIndex: "Username",
    fixed: 'left',
    width: 100,
    render: (text) => (
      <Link href="https://ant.design" target="_blank">
        {text}
      </Link>
    ),
  },
  {
    title: "ID",
    dataIndex: "id",
    width: 100,
  },
  {
    title: "Total Reach",
    dataIndex: "Total Reach",
    width: 100,
  },
  {
    title: "Engagement Rate",
    dataIndex: "Engagement Rate",
    width: 100,
  },
  {
    title: "Submitted Date/Time",
    dataIndex: "id",
    width: 100,
  },
  {
    title: "Tickets Earned",
    dataIndex: "Tickets Earned",
    width: 100,
  },
  {
    title: "Tokens Earned",
    dataIndex: "Tokens Earned",
    width: 100,
  },
  {
    title: "Stars Earned",
    dataIndex: "Stars Earned",
    width: 100,
  },
  {
    title: "Link To Content",
    dataIndex: "Link To Content",
    fixed: 'right',
    width: 100,
    render: (text) => (
      <Link href="https://ant.design" target="_blank">
        {text}
      </Link>
    ),
  },
];

export default function Home() {
  const { data } = useSwr("/api/submission", fetcher);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Space direction="vertical">
        <>
          <Link href="/">
       Home
      </Link>
      <Link href="/submission">
      Submission
      </Link></>
        <Title level={3}>User Submission</Title>
        <Table columnsData={columns} dataSource={data} />
        </Space>
  
      </main>
    </div>
  );
}
